Copyright Jana Schaich Borg/Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)

# MySQL Exercise 7: Joining Tables with Inner Joins

Before completing these exercises, I strongly recommend that you watch the video called "What are Joins?" that describe what joins are, and how different types of joins work.

As one of the last building blocks we need to address our Dognition analysis questions, in this lesson we will learn how to combine tables using inner joins.

   
## 1. Inner Joins between 2 tables

To begin, load the sql library, connect to the Dognition database, and set the Dognition database as the default.

In [1]:
%load_ext sql
%sql mysql://studentuser:studentpw@mysqlserver/dognitiondb
%sql USE dognitiondb

0 rows affected.


[]

Recall that tables in relational databases are linked through primary keys and sometimes other fields that are common to multiple tables (as is the case with our Dognition data set).  Our goal when we execute a JOIN or make a joined table is to use those common columns to let the database figure out which rows in one table match up to which rows in another table.  Once that mapping is established using at least one common field or column, the database can pull any columns you want out of the mapped, or joined, tables and output the matched data to one common table.

An inner join is a join that outputs only rows that have an exact match in both tables being joined:

<img src="https://duke.box.com/shared/static/xazeqtyq6bjo12ojvgxup4bx0e9qcn5d.jpg" width=400 alt="INNER_JOIN" />

To illustrate how this works, let's find out whether dog owners that are particularly surprised by their dog's performance on Dognition tests tend to own similar breeds (or breed types, or breed groups) of dogs.  There are many ways to address this question, but let's start by focusing on the dog owners who provided at least 10 ratings for one or more of their dogs in the ratings table. Of these owners, which 200 owners reported the highest average amount of surprise at their dog's performance, and what was the breed, breed_type, and breed_group of each of these owner's dog?

The surprise ratings are stored in the reviews table.  The dog breed information is provided in the dogs table.  There are two columns that are common to both tables: user_guid and dog_guid. How do we use the common columns to combine information from the two tables? 

To join the tables, you can use a WHERE clause and add a couple of details to the FROM clause so that the database knows from what table each field in your SELECT clause comes.  

First, start by adding all the columns we want to examine to the SELECT statement:

```mySQL
SELECT dog_guid AS DogID, user_guid AS UserID, AVG(rating) AS AvgRating, 
       COUNT(rating) AS NumRatings, breed, breed_group, breed_type
```
then list all the tables from which the fields we are interested in come, separated by commas (with no comma at the end of the list):

```mySQL
FROM dogs, reviews
```
then add the other restrictions:

```mySQL
GROUP BY user_guid
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

**Try running this query and see what happens:**



In [2]:
%%sql
SELECT   dog_guid AS DogID, user_guid AS UserID, AVG(rating) AS AvgRating, 
         COUNT(rating) AS NumRatings, breed, breed_group, breed_type
FROM     dogs, reviews
GROUP BY user_guid
HAVING   NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT    200

(_mysql_exceptions.OperationalError) (1052, "Column 'dog_guid' in field list is ambiguous") [SQL: 'SELECT   dog_guid AS DogID, user_guid AS UserID, AVG(rating) AS AvgRating, \n         COUNT(rating) AS NumRatings, breed, breed_group, breed_type\nFROM     dogs, reviews\nGROUP BY user_guid\nHAVING   NumRatings >= 10\nORDER BY AvgRating DESC\nLIMIT    200']


You should receive an error message stating that the identity of dog_guid and user_guid in the field list is ambiguous. The reason is that the column title exists in both tables, and MySQL doesn't know which one we want. We have to specify the table name before stating the field name, and separate the two names by a period <mark>(NOTE: read this entire section before deciding whether you want to execute this query)<mark\>:

```mySQL
SELECT dogs.dog_guid AS DogID, dogs.user_guid AS UserID, AVG(reviews.rating) AS AvgRating,     
       COUNT(reviews.rating) AS NumRatings, dogs.breed, dogs.breed_group, dogs.breed_type
FROM dogs, reviews
GROUP BY dogs.user_guid
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```


You can also take advantage of aliases so that you don't have to write out the name of the tables each time.  Here I will introduce another syntax for aliases that omits the AS completely.  In this syntax, the alias is whatever word (or phrase, if you use quotation marks) follows immediately after the field or table name, separated by a space.  So we could write:

```mySQL
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
GROUP BY d.user_guid
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

I am tempted to tell you to run this query so that you will see what happens, but instead, I will explain what will happen and let you decide if you want to see what the output looks...and feels...like.  
      
There is nothing built into the database table definitions that can instruct the server how to combine the tables on its own (remember, this is how relational databases save space and remain flexible).  Further, the query as written does not tell the database how the two tables are related.  As a consequence, rather than match up the two tables according to the values in the user_id and/or dog_id column, the database will do the only thing it knows how to do which is output every single combination of the records in the dogs table with the records in the reviews table.  In other words, every single row of the dogs table will get paired with every single row of the reviews table.  This is known as a Cartesian product.  Not only will it be a heavy burden on the database to output a table that has the full length of one table multiplied times the full length of another (and frustrating to you, because the query would take a very long time to run), the output would be close to useless.

To prevent this from happening, tell the database how to relate the tables in the WHERE clause:

```mySQL
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.dog_guid=r.dog_guid
GROUP BY d.user_guid
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

To be very careful and exclude any incorrect dog_guid or user_guid entries, you can include both shared columns in the WHERE clause:

```mySQL
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.dog_guid=r.dog_guid AND d.user_guid=r.user_guid
GROUP BY d.user_guid
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

**Try running this query now:**

In [3]:
%%sql
SELECT   d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
         COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM     dogs d, reviews r
WHERE    d.dog_guid=r.dog_guid AND d.user_guid=r.user_guid
GROUP BY d.user_guid
HAVING   NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT    200

38 rows affected.


[('fdbf39f8-7144-11e5-ba71-058fbc01cf0b', 'ce987914-7144-11e5-ba71-058fbc01cf0b', Decimal('8.0000'), 12, 'Canaan Dog', 'Herding', 'Pure Breed'),
 ('fdc09a82-7144-11e5-ba71-058fbc01cf0b', 'ce99bb12-7144-11e5-ba71-058fbc01cf0b', Decimal('5.0000'), 10, 'Golden Doodle', None, 'Popular Hybrid'),
 ('fdbef330-7144-11e5-ba71-058fbc01cf0b', 'ce984d2c-7144-11e5-ba71-058fbc01cf0b', Decimal('4.5385'), 13, 'Havanese', 'Toy', 'Pure Breed'),
 ('fdc0518a-7144-11e5-ba71-058fbc01cf0b', 'ce99661c-7144-11e5-ba71-058fbc01cf0b', Decimal('3.7333'), 15, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd684cf6-7144-11e5-ba71-058fbc01cf0b', 'ce473856-7144-11e5-ba71-058fbc01cf0b', Decimal('3.7222'), 18, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdbf66e4-7144-11e5-ba71-058fbc01cf0b', 'ce98b9b0-7144-11e5-ba71-058fbc01cf0b', Decimal('3.5000'), 14, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('fdc09b0e-7144-11e5-ba71-058fbc01cf0b', 'ce99bb76-7144-11e5-ba71-058fbc01cf0b', Decimal('3.2308'), 13, 'Golden Doodle', None, 'Popular Hybrid'),
 ('fdbeedc2-7144-11e5-ba71-058fbc01cf0b', 'ce9847dc-7144-11e5-ba71-058fbc01cf0b', Decimal('3.1538'), 13, 'Eurasier', None, 'Pure Breed'),
 ('fdc180be-7144-11e5-ba71-058fbc01cf0b', 'ce9a7110-7144-11e5-ba71-058fbc01cf0b', Decimal('3.0625'), 16, 'Chihuahua-Dachshund Mix', None, 'Cross Breed'),
 ('fd6aabd6-7144-11e5-ba71-058fbc01cf0b', 'ce6cd804-7144-11e5-ba71-058fbc01cf0b', Decimal('3.0000'), 13, 'American Pit Bull Terrier', None, 'Pure Breed'),
 ('fdbfc0b2-7144-11e5-ba71-058fbc01cf0b', 'ce98f3bc-7144-11e5-ba71-058fbc01cf0b', Decimal('2.6923'), 13, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbf96dc-7144-11e5-ba71-058fbc01cf0b', 'ce98ce0a-7144-11e5-ba71-058fbc01cf0b', Decimal('2.5714'), 14, 'American Pit Bull Terrier-American Staffordshire Terrier Mix', None, 'Cross Breed'),
 ('fdbedef4-7144-11e5-ba71-058fbc01cf0b', 'ce982e46-7144-11e5-ba71-058fbc01cf0b', Decimal('2.4615'), 13, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbec8ce-7144-11e5-ba71-058fbc01cf0b', 'ce980e3e-7144-11e5-ba71-058fbc01cf0b', Decimal('2.4545'), 11, 'Basset Hound', 'Hound', 'Pure Breed'),
 ('fdbeff06-7144-11e5-ba71-058fbc01cf0b', 'ce9856f0-7144-11e5-ba71-058fbc01cf0b', Decimal('2.4000'), 10, 'Bearded Collie', 'Herding', 'Pure Breed'),
 ('fdbed7ce-7144-11e5-ba71-058fbc01cf0b', 'ce981dc0-7144-11e5-ba71-058fbc01cf0b', Decimal('2.3333'), 18, 'Havanese', 'Toy', 'Pure Breed'),
 ('fdc1c31c-7144-11e5-ba71-058fbc01cf0b', 'ce9ac674-7144-11e5-ba71-058fbc01cf0b', Decimal('2.3077'), 13, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdc1a224-7144-11e5-ba71-058fbc01cf0b', 'ce9ab1f2-7144-11e5-ba71-058fbc01cf0b', Decimal('2.2857'), 14, 'Other', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc0c49e-7144-11e5-ba71-058fbc01cf0b', 'ce99d674-7144-11e5-ba71-058fbc01cf0b', Decimal('2.2778'), 18, 'Other', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc19b30-7144-11e5-ba71-058fbc01cf0b', 'ce9aab30-7144-11e5-ba71-058fbc01cf0b', Decimal('2.2222'), 18, 'Brittany', 'Sporting', 'Pure Breed'),
 ('fdc0c502-7144-11e5-ba71-058fbc01cf0b', 'ce99d732-7144-11e5-ba71-058fbc01cf0b', Decimal('2.0000'), 15, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('fdbedf94-7144-11e5-ba71-058fbc01cf0b', 'ce982ed2-7144-11e5-ba71-058fbc01cf0b', Decimal('2.0000'), 11, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd7104ae-7144-11e5-ba71-058fbc01cf0b', 'ce7212a6-7144-11e5-ba71-058fbc01cf0b', Decimal('1.9000'), 10, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc198d8-7144-11e5-ba71-058fbc01cf0b', 'ce9a9500-7144-11e5-ba71-058fbc01cf0b', Decimal('1.8000'), 10, 'German Shepherd Dog', 'Herding', 'Pure Breed'),
 ('fdbfddfe-7144-11e5-ba71-058fbc01cf0b', 'ce99049c-7144-11e5-ba71-058fbc01cf0b', Decimal('1.8000'), 40, 'Irish Water Spaniel', 'Sporting', 'Pure Breed'),
 ('fdbe923c-7144-11e5-ba71-058fbc01cf0b', 'ce97f926-7144-11e5-ba71-058fbc01cf0b', Decimal('1.7647'), 17, 'Beagle', 'Hound', 'Pure Breed'),
 ('fd6a7490-7144-11e5-ba71-058fbc01cf0b', 'ce6cf

The query should execute quickly.  This would NOT have been the case if you did not include the WHERE clause to combine the two tables. If you accidentally request a Cartesian product from datasets with billions of rows, you could be waiting for your query output for days (and will probably get in trouble with your database administrator).  <mark>So always remember to tell the database how to join your tables!</mark>

Let's examine our joined table a bit further.  The joined table outputted by the query above should have 38 rows, despite the fact that we set our LIMIT at 200.  The reason for this is that it turns out that a relatively small number of customers provided 10 or more reviews.  If you remove the HAVING and LIMIT BY clause from the query, you should end up with 389 rows.  **Go ahead and try it:**


In [4]:
%%sql
SELECT   d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
         COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM     dogs AS d, reviews AS r
WHERE    d.dog_guid=r.dog_guid AND d.user_guid=r.user_guid
GROUP BY d.user_guid
ORDER BY AvgRating DESC

389 rows affected.


[('fdc1c880-7144-11e5-ba71-058fbc01cf0b', 'ce96c768-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Maltese', 'Toy', 'Pure Breed'),
 ('fdbf178e-7144-11e5-ba71-058fbc01cf0b', 'ce986546-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Airedale Terrier', 'Terrier', 'Pure Breed'),
 ('fdbf94de-7144-11e5-ba71-058fbc01cf0b', 'ce98cc34-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 2, 'Pembroke Welsh Corgi', 'Herding', 'Pure Breed'),
 ('fdc019c2-7144-11e5-ba71-058fbc01cf0b', 'ce99489e-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc057ac-7144-11e5-ba71-058fbc01cf0b', 'ce996b9e-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc059fa-7144-11e5-ba71-058fbc01cf0b', 'ce996dc4-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Irish Water Spaniel', 'Sporting', 'Pure Breed'),
 ('fdc19554-7144-11e5-ba71-058fbc01cf0b', 'ce9a8a24-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Miniature Pinscher', 'Toy', 'Pure Breed'),
 ('fdc147ac-7144-11e5-ba71-058fbc01cf0b', 'ce9a545a-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Tibetan Terrier', 'Non-Sporting', 'Pure Breed'),
 ('fdc121dc-7144-11e5-ba71-058fbc01cf0b', 'ce9a310a-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbedd14-7144-11e5-ba71-058fbc01cf0b', 'ce975994-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbf39f8-7144-11e5-ba71-058fbc01cf0b', 'ce987914-7144-11e5-ba71-058fbc01cf0b', Decimal('8.0000'), 12, 'Canaan Dog', 'Herding', 'Pure Breed'),
 ('fd41bca8-7144-11e5-ba71-058fbc01cf0b', 'ce7b055a-7144-11e5-ba71-058fbc01cf0b', Decimal('8.0000'), 1, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdc1e1a8-7144-11e5-ba71-058fbc01cf0b', 'ce9ad934-7144-11e5-ba71-058fbc01cf0b', Decimal('7.5000'), 2, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc1baca-7144-11e5-ba71-058fbc01cf0b', 'ce9ac2fa-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 1, 'Poodle-Miniature Schnauzer Mix', None, 'Cross Breed'),
 ('fdbe7a40-7144-11e5-ba71-058fbc01cf0b', 'ce97df9a-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 6, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbe8774-7144-11e5-ba71-058fbc01cf0b', 'ce97ebfc-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 4, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdc2417a-7144-11e5-ba71-058fbc01cf0b', 'ce9b35e6-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 1, 'Bichon Frise', 'Non-Sporting', 'Pure Breed'),
 ('fdbf940c-7144-11e5-ba71-058fbc01cf0b', 'ce98cb80-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 1, 'Soft Coated Wheaten Terrier', 'Terrier', 'Pure Breed'),
 ('fdc1706a-7144-11e5-ba71-058fbc01cf0b', 'ce9a6846-7144-11e5-ba71-058fbc01cf0b', Decimal('6.8000'), 5, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc0c2aa-7144-11e5-ba71-058fbc01cf0b', 'ce99d322-7144-11e5-ba71-058fbc01cf0b', Decimal('6.5000'), 2, 'Border Collie', 'Herding', 'Pure Breed'),
 ('fdbf8598-7144-11e5-ba71-058fbc01cf0b', 'ce98c46e-7144-11e5-ba71-058fbc01cf0b', Decimal('6.5000'), 2, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdc0ef00-7144-11e5-ba71-058fbc01cf0b', 'ce99fe4c-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, "I Don't Know", None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbee278-7144-11e5-ba71-058fbc01cf0b', 'ce9782c0-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, 'Miniature Pinscher', 'Toy', 'Pure Breed'),
 ('fdc0cebc-7144-11e5-ba71-058fbc01cf0b', 'ce99ddd6-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 2, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc12d62-7144-11e5-ba71-058fbc01cf0b', 'ce9a381c-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, 'Chihuahua', 'Toy', 'Pure Breed'),
 ('fdbef2cc-7144-11e5-ba71-058fbc01cf0b', 'ce9838c8-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, 'Labradoodle', None, 'Popular Hybrid'),
 ('fdc01f76-7144-11e5-ba71-058fbc01cf0

It's clear from looking at this output that (A) not many customers provided ratings, and (B) when they did, they usually were not very surprised by their dog's performance.  Therefore, these ratings are probably not going to provide a lot of instructive insight into how to improve Dognition's completion rate.  However, the ratings table still provides a great opportunity to illustrate the results of different types of joins.  

To help prepare us for this:

**Questions 1-4:  How many unique dog_guids and user_guids are there in the reviews and dogs table independently?**  

In [5]:
%%sql
SELECT COUNT( DISTINCT( dog_guid ) ), COUNT( DISTINCT( user_guid ) )
FROM   dogs

1 rows affected.


[(35050, 30967)]

In [6]:
%%sql
SELECT COUNT( DISTINCT( dog_guid ) ), COUNT( DISTINCT( user_guid ) )
FROM   reviews

1 rows affected.


[(5991, 5586)]

These counts indicate some important things:

+ Many customers in both the reviews and the dogs table have multiple dogs
+ There are many more unique dog_guids and user_guids in the dogs table than the reviews table
+ There are many more unique dog_guids and user_guids in the reviews table than in the output of our inner join

Let's test one more thing.  
   
**Try the inner join query once with just the dog_guid or once with just the user_guid clause in the WHERE statement:**



In [7]:
%%sql
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM   dogs AS d, reviews AS r
WHERE  d.dog_guid = r.dog_guid
GROUP BY d.user_guid
ORDER BY AvgRating DESC

389 rows affected.


[('fdc1c880-7144-11e5-ba71-058fbc01cf0b', 'ce96c768-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Maltese', 'Toy', 'Pure Breed'),
 ('fdbf178e-7144-11e5-ba71-058fbc01cf0b', 'ce986546-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Airedale Terrier', 'Terrier', 'Pure Breed'),
 ('fdbf94de-7144-11e5-ba71-058fbc01cf0b', 'ce98cc34-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 2, 'Pembroke Welsh Corgi', 'Herding', 'Pure Breed'),
 ('fdc019c2-7144-11e5-ba71-058fbc01cf0b', 'ce99489e-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc057ac-7144-11e5-ba71-058fbc01cf0b', 'ce996b9e-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc059fa-7144-11e5-ba71-058fbc01cf0b', 'ce996dc4-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Irish Water Spaniel', 'Sporting', 'Pure Breed'),
 ('fdc19554-7144-11e5-ba71-058fbc01cf0b', 'ce9a8a24-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Miniature Pinscher', 'Toy', 'Pure Breed'),
 ('fdc147ac-7144-11e5-ba71-058fbc01cf0b', 'ce9a545a-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Tibetan Terrier', 'Non-Sporting', 'Pure Breed'),
 ('fdc121dc-7144-11e5-ba71-058fbc01cf0b', 'ce9a310a-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbedd14-7144-11e5-ba71-058fbc01cf0b', 'ce975994-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbf39f8-7144-11e5-ba71-058fbc01cf0b', 'ce987914-7144-11e5-ba71-058fbc01cf0b', Decimal('8.0000'), 12, 'Canaan Dog', 'Herding', 'Pure Breed'),
 ('fd41bca8-7144-11e5-ba71-058fbc01cf0b', 'ce7b055a-7144-11e5-ba71-058fbc01cf0b', Decimal('8.0000'), 1, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdc1e1a8-7144-11e5-ba71-058fbc01cf0b', 'ce9ad934-7144-11e5-ba71-058fbc01cf0b', Decimal('7.5000'), 2, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc1baca-7144-11e5-ba71-058fbc01cf0b', 'ce9ac2fa-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 1, 'Poodle-Miniature Schnauzer Mix', None, 'Cross Breed'),
 ('fdbe7a40-7144-11e5-ba71-058fbc01cf0b', 'ce97df9a-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 6, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbe8774-7144-11e5-ba71-058fbc01cf0b', 'ce97ebfc-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 4, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdc2417a-7144-11e5-ba71-058fbc01cf0b', 'ce9b35e6-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 1, 'Bichon Frise', 'Non-Sporting', 'Pure Breed'),
 ('fdbf940c-7144-11e5-ba71-058fbc01cf0b', 'ce98cb80-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 1, 'Soft Coated Wheaten Terrier', 'Terrier', 'Pure Breed'),
 ('fdc1706a-7144-11e5-ba71-058fbc01cf0b', 'ce9a6846-7144-11e5-ba71-058fbc01cf0b', Decimal('6.8000'), 5, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc0c2aa-7144-11e5-ba71-058fbc01cf0b', 'ce99d322-7144-11e5-ba71-058fbc01cf0b', Decimal('6.5000'), 2, 'Border Collie', 'Herding', 'Pure Breed'),
 ('fdbf8598-7144-11e5-ba71-058fbc01cf0b', 'ce98c46e-7144-11e5-ba71-058fbc01cf0b', Decimal('6.5000'), 2, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdc0ef00-7144-11e5-ba71-058fbc01cf0b', 'ce99fe4c-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, "I Don't Know", None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbee278-7144-11e5-ba71-058fbc01cf0b', 'ce9782c0-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, 'Miniature Pinscher', 'Toy', 'Pure Breed'),
 ('fdc0cebc-7144-11e5-ba71-058fbc01cf0b', 'ce99ddd6-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 2, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc12d62-7144-11e5-ba71-058fbc01cf0b', 'ce9a381c-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, 'Chihuahua', 'Toy', 'Pure Breed'),
 ('fdbef2cc-7144-11e5-ba71-058fbc01cf0b', 'ce9838c8-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, 'Labradoodle', None, 'Popular Hybrid'),
 ('fdc01f76-7144-11e5-ba71-058fbc01cf0

In [8]:
%%sql
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM   dogs AS d, reviews AS r
WHERE  d.user_guid = r.user_guid
GROUP BY d.user_guid
ORDER BY AvgRating DESC

5586 rows affected.


[('fd89a3b0-7144-11e5-ba71-058fbc01cf0b', 'ce7fc45a-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, "I Don't Know", None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd7537ea-7144-11e5-ba71-058fbc01cf0b', 'ce757f9a-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 2, 'German Shepherd Dog', 'Herding', 'Pure Breed'),
 ('fd6e8076-7144-11e5-ba71-058fbc01cf0b', 'ce6fcdb6-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fd51c72e-7144-11e5-ba71-058fbc01cf0b', 'ce32fd00-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Miniature Schnauzer', 'Terrier', 'Pure Breed'),
 ('fdb67b74-7144-11e5-ba71-058fbc01cf0b', 'ce91bfd4-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 2, 'American Pit Bull Terrier-Vizsla Mix', None, 'Cross Breed'),
 ('fdba5780-7144-11e5-ba71-058fbc01cf0b', 'ce956d78-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Maltese-Bichon Frise Mix', None, 'Cross Breed'),
 ('fd6ee764-7144-11e5-ba71-058fbc01cf0b', 'ce6fe8c8-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Pyrenean Shepherd', 'Herding', 'Pure Breed'),
 ('fdc059fa-7144-11e5-ba71-058fbc01cf0b', 'ce996dc4-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Irish Water Spaniel', 'Sporting', 'Pure Breed'),
 ('fdb3cf6e-7144-11e5-ba71-058fbc01cf0b', 'ce8a916e-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdc1c880-7144-11e5-ba71-058fbc01cf0b', 'ce96c768-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 2, 'Maltese', 'Toy', 'Pure Breed'),
 ('fdb75c4c-7144-11e5-ba71-058fbc01cf0b', 'ce927938-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Labradoodle', None, 'Popular Hybrid'),
 ('fd898934-7144-11e5-ba71-058fbc01cf0b', 'ce7fb1b8-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Newfoundland', 'Working', 'Pure Breed'),
 ('fdb92982-7144-11e5-ba71-058fbc01cf0b', 'ce944a88-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Jack Russell Terrier-Beagle Mix', None, 'Cross Breed'),
 ('fd6ac47c-7144-11e5-ba71-058fbc01cf0b', 'ce6d4c80-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'German Shepherd Dog-Boxer Mix', None, 'Cross Breed'),
 ('fdb9f95c-7144-11e5-ba71-058fbc01cf0b', 'ce9501d0-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 2, "I Don't Know", None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd740cc6-7144-11e5-ba71-058fbc01cf0b', 'ce749972-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd72d964-7144-11e5-ba71-058fbc01cf0b', 'ce739f40-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Border Collie', 'Herding', 'Pure Breed'),
 ('fdb4d0bc-7144-11e5-ba71-058fbc01cf0b', 'ce8ba4a0-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('fd43c4b2-7144-11e5-ba71-058fbc01cf0b', 'ce27023e-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 2, 'Mixed', '', "Mixed Breed/ Other/ I Don't Know"),
 ('fd89a284-7144-11e5-ba71-058fbc01cf0b', 'ce7fc400-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Jack Russell Terrier', 'Terrier', 'Pure Breed'),
 ('fdbd56c4-7144-11e5-ba71-058fbc01cf0b', 'ce970dea-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 2, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdacbda0-7144-11e5-ba71-058fbc01cf0b', 'ce8311d2-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 4, 'Collie', 'Herding', 'Pure Breed'),
 ('fd819f9e-7144-11e5-ba71-058fbc01cf0b', 'ce7e1362-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 2, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdb52c88-7144-11e5-ba71-058fbc01cf0b', 'ce8c11a6-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Standard Poodle', 'Non-Sporting', 'Pure Breed'),
 ('fdb250f8-7144-11e5-ba71-058fbc01cf0b', 'ce88c442-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Yorkshire Terrier', 'Toy', 'Pure Breed'),
 ('fdb786a4-7144-11e5-ba71-058fbc01cf0b', 'ce92ca64-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Australian Shepherd', 'Herding', 'Pure Breed'),
 ('fdaa4656-7144-11e5-ba7

When you run the query by joining on the dog_guid only, you still get 389 rows in your output.  When you run the query by joining on the user_guid only, you get 5586 rows in your output.  This means that:

+ All of the user_guids in the reviews table are in the dogs table
+ Only 389 of the over 5000 dog_guids in the reviews table are in the dogs table

Perhaps most importantly for our current purposes, these COUNT queries show you that <mark>*inner joins only output the data from rows that have equivalent values in both tables being joined*.</mark>  If you wanted to include all the dog_guids or user_guids in one or both of the tables, you would have to use an outer join, which we will practice in the next lesson.

Try an inner join on your own.  
   

**Question 5: How would you extract the user_guid, dog_guid, breed, breed_type, and breed_group for all animals who completed the "Yawn Warm-up" game (you should get 20,845 rows if you join on dog_guid only)?**

In [9]:
%%sql
SELECT d.user_guid, d.dog_guid, breed, breed_type, breed_group
FROM   dogs AS d, complete_tests AS c
WHERE  d.dog_guid = c.dog_guid AND test_name = "Yawn Warm-up"

20845 rows affected.


[('ce134e42-7144-11e5-ba71-058fbc01cf0b', 'fd27b272-7144-11e5-ba71-058fbc01cf0b', 'Labrador Retriever', 'Pure Breed', 'Sporting'),
 ('ce1353d8-7144-11e5-ba71-058fbc01cf0b', 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b', 'Shetland Sheepdog', 'Pure Breed', 'Herding'),
 ('ce135ab8-7144-11e5-ba71-058fbc01cf0b', 'fd27b6b4-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever', 'Pure Breed', 'Sporting'),
 ('ce13507c-7144-11e5-ba71-058fbc01cf0b', 'fd27b79a-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever', 'Pure Breed', 'Sporting'),
 ('ce135e14-7144-11e5-ba71-058fbc01cf0b', 'fd27b86c-7144-11e5-ba71-058fbc01cf0b', 'Shih Tzu', 'Pure Breed', 'Toy'),
 ('ce13615c-7144-11e5-ba71-058fbc01cf0b', 'fd27b948-7144-11e5-ba71-058fbc01cf0b', 'Siberian Husky', 'Pure Breed', 'Working'),
 ('ce135e14-7144-11e5-ba71-058fbc01cf0b', 'fd27ba1a-7144-11e5-ba71-058fbc01cf0b', 'Shih Tzu', 'Pure Breed', 'Toy'),
 ('ce135f2c-7144-11e5-ba71-058fbc01cf0b', 'fd27bbbe-7144-11e5-ba71-058fbc01cf0b', 'Mixed', "Mixed Breed/ Other/ I Don't Know", None),
 ('ce136a1c-7144-11e5-ba71-058fbc01cf0b', 'fd27c1c2-7144-11e5-ba71-058fbc01cf0b', 'Labrador Retriever', 'Pure Breed', 'Sporting'),
 ('ce136ac6-7144-11e5-ba71-058fbc01cf0b', 'fd27c5be-7144-11e5-ba71-058fbc01cf0b', 'Shih Tzu-Poodle Mix', 'Cross Breed', None),
 ('ce136c24-7144-11e5-ba71-058fbc01cf0b', 'fd27c74e-7144-11e5-ba71-058fbc01cf0b', 'German Shepherd Dog-Pembroke Welsh Corgi Mix', 'Cross Breed', None),
 ('ce136e36-7144-11e5-ba71-058fbc01cf0b', 'fd27c7d0-7144-11e5-ba71-058fbc01cf0b', 'Vizsla', 'Pure Breed', 'Sporting'),
 ('ce136ee0-7144-11e5-ba71-058fbc01cf0b', 'fd27c852-7144-11e5-ba71-058fbc01cf0b', 'Pug', 'Pure Breed', 'Toy'),
 ('ce136f94-7144-11e5-ba71-058fbc01cf0b', 'fd27c8d4-7144-11e5-ba71-058fbc01cf0b', 'Boxer', 'Pure Breed', 'Working'),
 ('ce134be0-7144-11e5-ba71-058fbc01cf0b', 'fd27c956-7144-11e5-ba71-058fbc01cf0b', 'German Shepherd Dog-Nova Scotia Duck Tolling Retriever Mix', 'Cross Breed', None),
 ('ce1371a6-7144-11e5-ba71-058fbc01cf0b', 'fd27cb72-7144-11e5-ba71-058fbc01cf0b', 'Beagle', 'Pure Breed', 'Hound'),
 ('ce136f94-7144-11e5-ba71-058fbc01cf0b', 'fd27cd98-7144-11e5-ba71-058fbc01cf0b', 'Beagle', 'Pure Breed', 'Hound'),
 ('ce136f94-7144-11e5-ba71-058fbc01cf0b', 'fd27ce1a-7144-11e5-ba71-058fbc01cf0b', 'Beagle', 'Pure Breed', 'Hound'),
 ('ce1373ae-7144-11e5-ba71-058fbc01cf0b', 'fd27cea6-7144-11e5-ba71-058fbc01cf0b', 'Mixed', "Mixed Breed/ Other/ I Don't Know", None),
 ('ce13750c-7144-11e5-ba71-058fbc01cf0b', 'fd27cf28-7144-11e5-ba71-058fbc01cf0b', 'Chesapeake Bay Retriever', 'Pure Breed', 'Sporting'),
 ('ce1375b6-7144-11e5-ba71-058fbc01cf0b', 'fd27cfaa-7144-11e5-ba71-058fbc01cf0b', 'Border Collie', 'Pure Breed', 'Herding'),
 ('ce1377b4-7144-11e5-ba71-058fbc01cf0b', 'fd27d02c-7144-11e5-ba71-058fbc01cf0b', 'Belgian Malinois', 'Pure Breed', 'Herding'),
 ('ce137700-7144-11e5-ba71-058fbc01cf0b', 'fd27d0b8-7144-11e5-ba71-058fbc01cf0b', 'Australian Shepherd-German Shepherd Dog Mix', 'Cross Breed', None),
 ('ce137868-7144-11e5-ba71-058fbc01cf0b', 'fd27d144-7144-11e5-ba71-058fbc01cf0b', 'Poodle', 'Pure Breed', 'Non-Sporting'),
 ('ce137868-7144-11e5-ba71-058fbc01cf0b', 'fd27d1c6-7144-11e5-ba71-058fbc01cf0b', 'Poodle', 'Pure Breed', 'Non-Sporting'),
 ('ce137912-7144-11e5-ba71-058fbc01cf0b', 'fd27d248-7144-11e5-ba71-058fbc01cf0b', 'Golden Doodle', 'Popular Hybrid', None),
 ('ce1379c6-7144-11e5-ba71-058fbc01cf0b', 'fd27d2ca-7144-11e5-ba71-058fbc01cf0b', 'Labrador Retriever', 'Pure Breed', 'Sporting'),
 ('ce137a7a-7144-11e5-ba71-058fbc01cf0b', 'fd27d34c-7144-11e5-ba71-058fbc01cf0b', 'German Shepherd Dog', 'Pure Breed', 'Herding'),
 ('ce137a7a-7144-11e5-ba71-058fbc01cf0b', 'fd27d3d8-7144-11e5-ba71-058fbc01cf0b', 'German Shepherd Dog', 'Pure Breed', 'Herding'),
 ('ce137034-7144-11e5-ba71-058fbc01cf0b', 'fd27d45a-7144-11e5-ba71-058fbc01cf0b', 'Weimaraner', 'Pure Breed', 'Sporting'),
 ('ce137034-7144-11e5-ba71-058fbc01cf0b', 'fd27d4dc-7144-11e5-ba71-058fbc01cf0b', 'Mixed', "Mixed Breed/ Other/ I Don't Know", None),
 ('ce137c78-7144-11e5-ba

## 2. Joining More than 2 Tables

In theory, you can join as many tables together as you want or need.  To join multiple tables you take the same approach as we took when we were joining two tables together: list all the fields you want to extract in the SELECT statement, specify which table they came from in the SELECT statement, list all the tables from which you will need to extract the fields in the FROM statement, and then tell the database how to connect the tables in the WHERE statement.

To extract the user_guid, user's state of residence, user's zip code, dog_guid, breed, breed_type, and breed_group for all animals who completed the "Yawn Warm-up" game, you might be tempted to query:

```mySQL
SELECT c.user_guid AS UserID, u.state, u.zip, d.dog_guid AS DogID, d.breed, d.breed_type, d.breed_group
FROM dogs d, complete_tests c, users u
WHERE d.dog_guid=c.dog_guid 
   AND c.user_guid=u.user_guid
   AND c.test_name="Yawn Warm-up";
```
This query focuses the relationships primarily on the complete_tests table.  However, it turns out that our Dognition dataset has only NULL values in the user_guid column of the complete_tests table.  If you were to execute the query above, you would not get an error message, but your output would have 0 rows.  However, the power of relational databases will come in handy here.  You can use the dogs table to link the complete_tests and users table (pay attention to the difference between the WHERE statement in this query vs. the WHERE statement in the query above):

```mySQL
SELECT d.user_guid AS UserID, u.state, u.zip, d.dog_guid AS DogID, d.breed, d.breed_type, d.breed_group
FROM dogs d, complete_tests c, users u
WHERE d.dog_guid=c.dog_guid 
   AND d.user_guid=u.user_guid
   AND c.test_name="Yawn Warm-up";
```

Of note, joins are very resource intensive, so try not to join unnecessarily.  In general, the more joins you have to execute, the slower your query performance will be.

**Question 6: How would you extract the user_guid, membership_type, and dog_guid of all the golden retrievers who completed at least 1 Dognition test (you should get 711 rows)?**

In [10]:
%%sql
SELECT DISTINCT d.user_guid AS UserID, u.membership_type, d.dog_guid AS
DogID, d.breed
FROM dogs d, complete_tests c, users u
WHERE d.dog_guid=c.dog_guid
AND d.user_guid=u.user_guid
AND d.breed="golden retriever";

711 rows affected.


[('ce135ab8-7144-11e5-ba71-058fbc01cf0b', 1, 'fd27b6b4-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce13507c-7144-11e5-ba71-058fbc01cf0b', 1, 'fd27b79a-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce1389d4-7144-11e5-ba71-058fbc01cf0b', 1, 'fd27efb2-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce21f122-7144-11e5-ba71-058fbc01cf0b', 2, 'fd3d03fc-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce220bb2-7144-11e5-ba71-058fbc01cf0b', 2, 'fd3d10cc-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce2237f4-7144-11e5-ba71-058fbc01cf0b', 2, 'fd3d3b24-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce2243e8-7144-11e5-ba71-058fbc01cf0b', 2, 'fd3d4b8c-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce240b24-7144-11e5-ba71-058fbc01cf0b', 2, 'fd3fe96e-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce24476a-7144-11e5-ba71-058fbc01cf0b', 2, 'fd404ff8-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce245cdc-7144-11e5-ba71-058fbc01cf0b', 2, 'fd4059e4-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce246be6-7144-11e5-ba71-058fbc01cf0b', 2, 'fd40738e-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce249774-7144-11e5-ba71-058fbc01cf0b', 1, 'fd408ed2-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce249c6a-7144-11e5-ba71-058fbc01cf0b', 2, 'fd40945e-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce24c1c2-7144-11e5-ba71-058fbc01cf0b', 2, 'fd40ee72-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce24a106-7144-11e5-ba71-058fbc01cf0b', 2, 'fd40f822-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce24d572-7144-11e5-ba71-058fbc01cf0b', 2, 'fd4107cc-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce24d914-7144-11e5-ba71-058fbc01cf0b', 2, 'fd410cb8-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce24de50-7144-11e5-ba71-058fbc01cf0b', 1, 'fd411690-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce24e116-7144-11e5-ba71-058fbc01cf0b', 1, 'fd4118e8-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce24e684-7144-11e5-ba71-058fbc01cf0b', 2, 'fd411b0e-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce253a6c-7144-11e5-ba71-058fbc01cf0b', 2, 'fd418b02-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce2556a0-7144-11e5-ba71-058fbc01cf0b', 1, 'fd41c5f4-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce255c54-7144-11e5-ba71-058fbc01cf0b', 2, 'fd41c84c-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce257fc2-7144-11e5-ba71-058fbc01cf0b', 2, 'fd41db34-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce2585a8-7144-11e5-ba71-058fbc01cf0b', 2, 'fd41e232-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce22680a-7144-11e5-ba71-058fbc01cf0b', 1, 'fd41e28c-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce258a08-7144-11e5-ba71-058fbc01cf0b', 2, 'fd41e796-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce259dd6-7144-11e5-ba71-058fbc01cf0b', 1, 'fd421400-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce25c306-7144-11e5-ba71-058fbc01cf0b', 1, 'fd423f70-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce25caa4-7144-11e5-ba71-058fbc01cf0b', 2, 'fd4244f2-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce25f4de-7144-11e5-ba71-058fbc01cf0b', 2, 'fd4275a8-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce26092e-7144-11e5-ba71-058fbc01cf0b', 1, 'fd42933a-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce261a40-7144-11e5-ba71-058fbc01cf0b', 1, 'fd42a29e-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce261bd0-7144-11e5-ba71-058fbc01cf0b', 2, 'fd42a366-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce261ffe-7144-11e5-ba71-058fbc01cf0b', 2, 'fd42ab9a-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce262062-7144-11e5-ba71-058fbc01cf0b', 2, 'fd42abfe-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce26280a-7144-11e5-ba71-058fbc01cf0b', 2, 'fd42c51c-7144-11e5-ba71-058fbc01cf0b', 'Golden Retriever'),
 ('ce263782-7144-11e5-ba71-058fbc01cf0b', 2, 'fd42e6e6-7144-11e5-ba71-058fbc01

In [11]:
%%sql
SELECT u.user_guid, d.dog_guid, u.membership_type, COUNT( d.total_tests_completed )
FROM   dogs AS d, users AS u
WHERE d.user_guid = u.user_guid AND breed = "Golden Retriever"
GROUP BY d.dog_guid
HAVING COUNT( d.total_tests_completed ) >= 1

711 rows affected.


[('ce135ab8-7144-11e5-ba71-058fbc01cf0b', 'fd27b6b4-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce13507c-7144-11e5-ba71-058fbc01cf0b', 'fd27b79a-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce1389d4-7144-11e5-ba71-058fbc01cf0b', 'fd27efb2-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce21f122-7144-11e5-ba71-058fbc01cf0b', 'fd3d03fc-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce220bb2-7144-11e5-ba71-058fbc01cf0b', 'fd3d10cc-7144-11e5-ba71-058fbc01cf0b', 2, 2),
 ('ce2237f4-7144-11e5-ba71-058fbc01cf0b', 'fd3d3b24-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce2243e8-7144-11e5-ba71-058fbc01cf0b', 'fd3d4b8c-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce240b24-7144-11e5-ba71-058fbc01cf0b', 'fd3fe96e-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce24476a-7144-11e5-ba71-058fbc01cf0b', 'fd404ff8-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce245cdc-7144-11e5-ba71-058fbc01cf0b', 'fd4059e4-7144-11e5-ba71-058fbc01cf0b', 2, 2),
 ('ce246be6-7144-11e5-ba71-058fbc01cf0b', 'fd40738e-7144-11e5-ba71-058fbc01cf0b', 2, 3),
 ('ce249774-7144-11e5-ba71-058fbc01cf0b', 'fd408ed2-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce249c6a-7144-11e5-ba71-058fbc01cf0b', 'fd40945e-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce24c1c2-7144-11e5-ba71-058fbc01cf0b', 'fd40ee72-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce24a106-7144-11e5-ba71-058fbc01cf0b', 'fd40f822-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce24d572-7144-11e5-ba71-058fbc01cf0b', 'fd4107cc-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce24d914-7144-11e5-ba71-058fbc01cf0b', 'fd410cb8-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce24de50-7144-11e5-ba71-058fbc01cf0b', 'fd411690-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce24e116-7144-11e5-ba71-058fbc01cf0b', 'fd4118e8-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce24e684-7144-11e5-ba71-058fbc01cf0b', 'fd411b0e-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce253a6c-7144-11e5-ba71-058fbc01cf0b', 'fd418b02-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce2556a0-7144-11e5-ba71-058fbc01cf0b', 'fd41c5f4-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce255c54-7144-11e5-ba71-058fbc01cf0b', 'fd41c84c-7144-11e5-ba71-058fbc01cf0b', 2, 2),
 ('ce257fc2-7144-11e5-ba71-058fbc01cf0b', 'fd41db34-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce2585a8-7144-11e5-ba71-058fbc01cf0b', 'fd41e232-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce22680a-7144-11e5-ba71-058fbc01cf0b', 'fd41e28c-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce258a08-7144-11e5-ba71-058fbc01cf0b', 'fd41e796-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce259dd6-7144-11e5-ba71-058fbc01cf0b', 'fd421400-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce25c306-7144-11e5-ba71-058fbc01cf0b', 'fd423f70-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce25caa4-7144-11e5-ba71-058fbc01cf0b', 'fd4244f2-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce25f4de-7144-11e5-ba71-058fbc01cf0b', 'fd4275a8-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce26092e-7144-11e5-ba71-058fbc01cf0b', 'fd42933a-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce261a40-7144-11e5-ba71-058fbc01cf0b', 'fd42a29e-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce261bd0-7144-11e5-ba71-058fbc01cf0b', 'fd42a366-7144-11e5-ba71-058fbc01cf0b', 2, 3),
 ('ce261ffe-7144-11e5-ba71-058fbc01cf0b', 'fd42ab9a-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce262062-7144-11e5-ba71-058fbc01cf0b', 'fd42abfe-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce26280a-7144-11e5-ba71-058fbc01cf0b', 'fd42c51c-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce263782-7144-11e5-ba71-058fbc01cf0b', 'fd42e6e6-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce263d72-7144-11e5-ba71-058fbc01cf0b', 'fd42ea1a-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce264cd6-7144-11e5-ba71-058fbc01cf0b', 'fd42f1b8-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce2660ea-7144-11e5-ba71-058fbc01cf0b', 'fd42fc62-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce266342-7144-11e5-ba71-058fbc01cf0b', 'fd42fece-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce266400-7144-11e5-ba71-058fbc01cf0b', 'fd42ff32-7144-11e5-ba71-058fbc01cf0b', 1, 1),
 ('ce26663a-7144-11e5-ba71-058fbc01cf0b', 'fd43020c-7144-11e5-ba71-058fbc01cf0b', 2, 1),
 ('ce266f18-7144-11e5-ba71-058fbc01cf0b', 'fd430dc4-7144-11e5-ba71-058fbc01cf0b', 1,

## Practice inner joining your own tables!

**Question 7: How many unique Golden Retrievers who live in North Carolina are there in the Dognition database (you should get 30)?**



In [12]:
%%sql
SELECT u.state, d.breed, COUNT( DISTINCT(d.dog_guid) )
FROM   dogs AS d, users AS u
WHERE  d.user_guid = u.user_guid AND d.breed = "Golden Retriever"
GROUP BY u.state
HAVING u.state = "NC"

1 rows affected.


[('NC', 'Golden Retriever', 30)]

**Question 8: How many unique customers within each membership type provided reviews (there should be 3208 in the membership type with the greatest number of customers, and 18 in the membership type with the fewest number of customers)?**

In [13]:
%%sql
SELECT u.membership_type, COUNT( DISTINCT u.user_guid )
FROM   users AS u, reviews AS r
WHERE  u.user_guid = r.user_guid
GROUP BY membership_type

5 rows affected.


[(1, 3208), (2, 1226), (3, 259), (4, 875), (5, 18)]

**Question 9: For which 3 dog breeds do we have the greatest amount of site_activity data, (as defined by non-NULL values in script_detail_id)(your answers should be "Mixed", "Labrador Retriever", and "Labrador Retriever-Golden Retriever Mix"?**

In [14]:
%%sql
SELECT d.breed, COUNT( s.script_detail_id ) AS site_activity
FROM   site_activities AS s, dogs AS d 
WHERE  s.user_guid = d.user_guid AND s.script_detail_id IS NOT NULL
GROUP BY breed
ORDER BY site_activity DESC
LIMIT 3

3 rows affected.


[('Mixed', 105669), ('Labrador Retriever', 44624), ('Shih Tzu', 40825)]

**Practice any other inner joins you would like to try here!**